// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"insightGlobal_carInventory/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCarStorage creates a new instance of MockCarStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarStorage {
	mock := &MockCarStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCarStorage is an autogenerated mock type for the CarStorage type
type MockCarStorage struct {
	mock.Mock
}

type MockCarStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarStorage) EXPECT() *MockCarStorage_Expecter {
	return &MockCarStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCarStorage
func (_mock *MockCarStorage) Create(ctx context.Context, car *model.Car) error {
	ret := _mock.Called(ctx, car)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Car) error); ok {
		r0 = returnFunc(ctx, car)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCarStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - car *model.Car
func (_e *MockCarStorage_Expecter) Create(ctx interface{}, car interface{}) *MockCarStorage_Create_Call {
	return &MockCarStorage_Create_Call{Call: _e.mock.On("Create", ctx, car)}
}

func (_c *MockCarStorage_Create_Call) Run(run func(ctx context.Context, car *model.Car)) *MockCarStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Car
		if args[1] != nil {
			arg1 = args[1].(*model.Car)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarStorage_Create_Call) Return(err error) *MockCarStorage_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCarStorage_Create_Call) RunAndReturn(run func(ctx context.Context, car *model.Car) error) *MockCarStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCarStorage
func (_mock *MockCarStorage) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCarStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCarStorage_Expecter) Delete(ctx interface{}, id interface{}) *MockCarStorage_Delete_Call {
	return &MockCarStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarStorage_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCarStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarStorage_Delete_Call) Return(err error) *MockCarStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCarStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCarStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCarStorage
func (_mock *MockCarStorage) GetByID(ctx context.Context, id uuid.UUID) (*model.Car, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Car
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Car, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Car); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Car)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCarStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCarStorage_Expecter) GetByID(ctx interface{}, id interface{}) *MockCarStorage_GetByID_Call {
	return &MockCarStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCarStorage_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCarStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarStorage_GetByID_Call) Return(car *model.Car, err error) *MockCarStorage_GetByID_Call {
	_c.Call.Return(car, err)
	return _c
}

func (_c *MockCarStorage_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Car, error)) *MockCarStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCarStorage
func (_mock *MockCarStorage) List(ctx context.Context, pageSize int, pageNumber int) ([]*model.Car, error) {
	ret := _mock.Called(ctx, pageSize, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Car
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Car, error)); ok {
		return returnFunc(ctx, pageSize, pageNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*model.Car); ok {
		r0 = returnFunc(ctx, pageSize, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Car)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, pageSize, pageNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCarStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int
//   - pageNumber int
func (_e *MockCarStorage_Expecter) List(ctx interface{}, pageSize interface{}, pageNumber interface{}) *MockCarStorage_List_Call {
	return &MockCarStorage_List_Call{Call: _e.mock.On("List", ctx, pageSize, pageNumber)}
}

func (_c *MockCarStorage_List_Call) Run(run func(ctx context.Context, pageSize int, pageNumber int)) *MockCarStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCarStorage_List_Call) Return(cars []*model.Car, err error) *MockCarStorage_List_Call {
	_c.Call.Return(cars, err)
	return _c
}

func (_c *MockCarStorage_List_Call) RunAndReturn(run func(ctx context.Context, pageSize int, pageNumber int) ([]*model.Car, error)) *MockCarStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCarStorage
func (_mock *MockCarStorage) Update(ctx context.Context, car *model.Car) error {
	ret := _mock.Called(ctx, car)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Car) error); ok {
		r0 = returnFunc(ctx, car)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCarStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - car *model.Car
func (_e *MockCarStorage_Expecter) Update(ctx interface{}, car interface{}) *MockCarStorage_Update_Call {
	return &MockCarStorage_Update_Call{Call: _e.mock.On("Update", ctx, car)}
}

func (_c *MockCarStorage_Update_Call) Run(run func(ctx context.Context, car *model.Car)) *MockCarStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Car
		if args[1] != nil {
			arg1 = args[1].(*model.Car)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarStorage_Update_Call) Return(err error) *MockCarStorage_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCarStorage_Update_Call) RunAndReturn(run func(ctx context.Context, car *model.Car) error) *MockCarStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}
