// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPing creates a new instance of MockPing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPing(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPing {
	mock := &MockPing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPing is an autogenerated mock type for the Ping type
type MockPing struct {
	mock.Mock
}

type MockPing_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPing) EXPECT() *MockPing_Expecter {
	return &MockPing_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockPing
func (_mock *MockPing) Ping(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPing_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPing_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPing_Expecter) Ping(context1 interface{}) *MockPing_Ping_Call {
	return &MockPing_Ping_Call{Call: _e.mock.On("Ping", context1)}
}

func (_c *MockPing_Ping_Call) Run(run func(context1 context.Context)) *MockPing_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPing_Ping_Call) Return(err error) *MockPing_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPing_Ping_Call) RunAndReturn(run func(context1 context.Context) error) *MockPing_Ping_Call {
	_c.Call.Return(run)
	return _c
}
