// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"insightGlobal_carInventory/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CarStorage provides a mock function for the type MockRepository
func (_mock *MockRepository) CarStorage() repository.CarStorage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CarStorage")
	}

	var r0 repository.CarStorage
	if returnFunc, ok := ret.Get(0).(func() repository.CarStorage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.CarStorage)
		}
	}
	return r0
}

// MockRepository_CarStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CarStorage'
type MockRepository_CarStorage_Call struct {
	*mock.Call
}

// CarStorage is a helper method to define mock.On call
func (_e *MockRepository_Expecter) CarStorage() *MockRepository_CarStorage_Call {
	return &MockRepository_CarStorage_Call{Call: _e.mock.On("CarStorage")}
}

func (_c *MockRepository_CarStorage_Call) Run(run func()) *MockRepository_CarStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_CarStorage_Call) Return(carStorage repository.CarStorage) *MockRepository_CarStorage_Call {
	_c.Call.Return(carStorage)
	return _c
}

func (_c *MockRepository_CarStorage_Call) RunAndReturn(run func() repository.CarStorage) *MockRepository_CarStorage_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockRepository
func (_mock *MockRepository) Ping(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) Ping(context1 interface{}) *MockRepository_Ping_Call {
	return &MockRepository_Ping_Call{Call: _e.mock.On("Ping", context1)}
}

func (_c *MockRepository_Ping_Call) Run(run func(context1 context.Context)) *MockRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Ping_Call) Return(err error) *MockRepository_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Ping_Call) RunAndReturn(run func(context1 context.Context) error) *MockRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}
