// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthCheckService creates a new instance of MockHealthCheckService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckService {
	mock := &MockHealthCheckService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthCheckService is an autogenerated mock type for the HealthCheckService type
type MockHealthCheckService struct {
	mock.Mock
}

type MockHealthCheckService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckService) EXPECT() *MockHealthCheckService_Expecter {
	return &MockHealthCheckService_Expecter{mock: &_m.Mock}
}

// PingMysql provides a mock function for the type MockHealthCheckService
func (_mock *MockHealthCheckService) PingMysql(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingMysql")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthCheckService_PingMysql_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingMysql'
type MockHealthCheckService_PingMysql_Call struct {
	*mock.Call
}

// PingMysql is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthCheckService_Expecter) PingMysql(ctx interface{}) *MockHealthCheckService_PingMysql_Call {
	return &MockHealthCheckService_PingMysql_Call{Call: _e.mock.On("PingMysql", ctx)}
}

func (_c *MockHealthCheckService_PingMysql_Call) Run(run func(ctx context.Context)) *MockHealthCheckService_PingMysql_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthCheckService_PingMysql_Call) Return(err error) *MockHealthCheckService_PingMysql_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthCheckService_PingMysql_Call) RunAndReturn(run func(ctx context.Context) error) *MockHealthCheckService_PingMysql_Call {
	_c.Call.Return(run)
	return _c
}
