// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package infrastructure

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockDB
func (_mock *MockDB) Connect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDB_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockDB_Expecter) Connect() *MockDB_Connect_Call {
	return &MockDB_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockDB_Connect_Call) Run(run func()) *MockDB_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Connect_Call) Return(err error) *MockDB_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_Connect_Call) RunAndReturn(run func() error) *MockDB_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockDB
func (_mock *MockDB) Insert() *bun.InsertQuery {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *bun.InsertQuery
	if returnFunc, ok := ret.Get(0).(func() *bun.InsertQuery); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bun.InsertQuery)
		}
	}
	return r0
}

// MockDB_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockDB_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
func (_e *MockDB_Expecter) Insert() *MockDB_Insert_Call {
	return &MockDB_Insert_Call{Call: _e.mock.On("Insert")}
}

func (_c *MockDB_Insert_Call) Run(run func()) *MockDB_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Insert_Call) Return(insertQuery *bun.InsertQuery) *MockDB_Insert_Call {
	_c.Call.Return(insertQuery)
	return _c
}

func (_c *MockDB_Insert_Call) RunAndReturn(run func() *bun.InsertQuery) *MockDB_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// IsAlive provides a mock function for the type MockDB
func (_mock *MockDB) IsAlive() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAlive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_IsAlive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAlive'
type MockDB_IsAlive_Call struct {
	*mock.Call
}

// IsAlive is a helper method to define mock.On call
func (_e *MockDB_Expecter) IsAlive() *MockDB_IsAlive_Call {
	return &MockDB_IsAlive_Call{Call: _e.mock.On("IsAlive")}
}

func (_c *MockDB_IsAlive_Call) Run(run func()) *MockDB_IsAlive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_IsAlive_Call) Return(err error) *MockDB_IsAlive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_IsAlive_Call) RunAndReturn(run func() error) *MockDB_IsAlive_Call {
	_c.Call.Return(run)
	return _c
}

// PingContext provides a mock function for the type MockDB
func (_mock *MockDB) PingContext() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockDB_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
func (_e *MockDB_Expecter) PingContext() *MockDB_PingContext_Call {
	return &MockDB_PingContext_Call{Call: _e.mock.On("PingContext")}
}

func (_c *MockDB_PingContext_Call) Run(run func()) *MockDB_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_PingContext_Call) Return(err error) *MockDB_PingContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_PingContext_Call) RunAndReturn(run func() error) *MockDB_PingContext_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockDB
func (_mock *MockDB) Select() *bun.SelectQuery {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 *bun.SelectQuery
	if returnFunc, ok := ret.Get(0).(func() *bun.SelectQuery); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bun.SelectQuery)
		}
	}
	return r0
}

// MockDB_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockDB_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
func (_e *MockDB_Expecter) Select() *MockDB_Select_Call {
	return &MockDB_Select_Call{Call: _e.mock.On("Select")}
}

func (_c *MockDB_Select_Call) Run(run func()) *MockDB_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Select_Call) Return(selectQuery *bun.SelectQuery) *MockDB_Select_Call {
	_c.Call.Return(selectQuery)
	return _c
}

func (_c *MockDB_Select_Call) RunAndReturn(run func() *bun.SelectQuery) *MockDB_Select_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDB
func (_mock *MockDB) Update() *bun.UpdateQuery {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *bun.UpdateQuery
	if returnFunc, ok := ret.Get(0).(func() *bun.UpdateQuery); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bun.UpdateQuery)
		}
	}
	return r0
}

// MockDB_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDB_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockDB_Expecter) Update() *MockDB_Update_Call {
	return &MockDB_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockDB_Update_Call) Run(run func()) *MockDB_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Update_Call) Return(updateQuery *bun.UpdateQuery) *MockDB_Update_Call {
	_c.Call.Return(updateQuery)
	return _c
}

func (_c *MockDB_Update_Call) RunAndReturn(run func() *bun.UpdateQuery) *MockDB_Update_Call {
	_c.Call.Return(run)
	return _c
}
